/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef GAUSEXPBACKGROUND
#define GAUSEXPBACKGROUND

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class GausExpShape : public RooAbsPdf {
public:
  GausExpShape() {} ; 
  GausExpShape(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _x0,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha);
  GausExpShape(const GausExpShape& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new GausExpShape(*this,newname); }
  inline virtual ~GausExpShape() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy x ;
  RooRealProxy x0 ;
  RooRealProxy sigma ;
  RooRealProxy alpha ;
  
  Double_t evaluate() const ;

private:

  ClassDef(GausExpShape,1) // A generic background shape with a gaussian turn on and an exponential tail
};
 
#endif
